version: "3.7"
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: dude
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    networks:
      - database

  rabbit:
    image: rabbit:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      database

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - database
      - rabbit
    networks:
      - database

networks:
  database:
    driver: bridge