version: "3.7"
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: dude
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    networks:
      - database

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - database

networks:
  database:
    driver: bridge