version: "3.7"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    networks:
      - database

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - database

networks:
  database:
    driver: bridge