version: "3.3"
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: dude
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql

  app:
    image: 961070163841.dkr.ecr.us-east-2.amazonaws.com/kursach:latest
    ports:
      - "80:3000"
    depends_on:
      - database
